### ISSUE TITLE
When I use this theme on Shopify, no payment icon appears, although I checked the payment icon

### ISSUE THREAD

**Issue by Ellahappy** [kondasoft/ks-bootshop#103]
![微信图片_20240828172533](https://github.com/user-attachments/assets/542f4e88-bf7f-4a2b-b686-09ba3f944a2c)

**Comment by alvinkonda** [comment]
Hi,

The icons are automatically shown by Shopify according to the enabled payment methods on your Shopify store.
https://help.shopify.com/en/manual/payments/shopify-payments/setting-up-shopify-payments

If you are just starting out and want to test the payment you may enable the Bogus gateway like we do on our demos for example.
https://help.shopify.com/en/manual/payments/shopify-payments/testing-shopify-payments
