### ISSUE TITLE
Question - how does the theme redirect to checkout from the mini cart?

### ISSUE THREAD

**Issue by chunkysteveo** [kondasoft/ks-bootshop#43]
Hi - great theme, and the BS4 version too. But I have a question which has stumped me - when I add an item to the cart, how does the mini cart work when clicking "Checkout"? From what I can see it should submit to /cart, but it takes you direct to the checkout. When I copy the theme this works, but when I copy just the mini cart "form" the checkout button takes you to the cart.

Looking through the code for hints how the site knows to go to the checkout - I am stumped!

Thanks in advance!

Steve

**Comment by alvinkonda** [comment]
Hi Steve,
Thanks for your kind words.

First I'm assuming that you are working with BS5 version. So I guess the checkout link is working fine. It just redirects you to the checkout page, why you need to submit to the cart?  If the client wants to view the cart he may simply click the other button, (View cart). Please provide additional info so that I can better understand your issue.

**Comment by chunkysteveo** [comment]
Hey Alvin, thanks for getting back!! They really are great themes to work with and get inspiration from!

So.. This is all within mini-cart.liquid. 

The mini cart has the form set to POST to /cart. 

`<form method="post" action="/cart">`

There is a Cart button that is an anchor link that goes to /cart, and the Checkout button is a Button, which you would assume submits the mini cart form, but that's set to POST to /cart, not /checkout?

It works fine in the BS5 demo you have, but I have been working with the BS4 version, and have copied over the mini-cart html/liquid and layout, and was trying to get the mini-cart checkout button to go to the checkout using the same code. Currently if I use the mini-cart code from the BS5 demo and use it on my theme and click Checkout - it takes me to the /cart.

That's why I was curious, as the code looks like that is what would happen, submit the form to the cart, but the demo works as you would expect the Checkout button to do.

It's odd, and was wondering if I have just missed an obvious thing that is included in the BS5 theme that handles the mini-cart submission, or the cart-to-checkout-redirect?

Cheers,

Steve

**Comment by alvinkonda** [comment]
The only obvious thing that I think you might have missed is the attribute `name="checkout"` on the Checkout button. If not the case, I have to check your store to see what's the issue.

**Comment by chunkysteveo** [comment]
Thanks, but i've included that - I assumed the name="checkout" on the button would set off something, but it's not the case. Like I said - it's odd!!

It's not a major thing, I have a manual work around to send users to the checkout on the button, but I was curious about the more elegant form of not actually having the link direct to the checkout.

I will have a play some more and figure it out. If I do - i'll let you know how it was breaking and what fixed it!

Cheers,

Steve

**Comment by alvinkonda** [comment]
Ok, sure. If want that i have look into it, just let me know the store url

**Comment by chunkysteveo** [comment]
Hey @alvinkonda  - FYI I got it figured out! Turns out the ReCharge Payments application default JavaScript that is added to a shopify site adds a custom function on the mini-cart button name to check and redirect to CART only, and I had to amend it to work for our needs for the mini-cart. All sorted - keep up your great work, all the best!

Steve

**Comment by alvinkonda** [comment]
That's good to know. Feel free to let us know if you need anything else
