### ISSUE TITLE
Add to Cart unresponsive with QTY hidden

### ISSUE THREAD

**Issue by cleayp** [kondasoft/ks-bootshop#49]
The Add to Cart button hangs when the 'Show quantity' option is checked; the button dims and the spinner spins indefinitely.

Fixed by editing the qty input in the add to cart form on the product-template.liquid file:
Move the {% if section.settings.show_qty %} conditional to change the input type from 'number' to 'hidden':
```
<input
    id="qty"
    {% if section.settings.show_qty %}
    type="number"
    {% else %}
    type="hidden"
    {% endif %}
    class="form-control me-2"
    size="20" 
    name="quantity" 
    value="1" 
    min="1"
    data-bs-toggle="tooltip" 
    data-bs-placement="bottom" 
    aria-label="{{ 'product.quantity' | t }}"
    title="{{ 'product.quantity' | t }}"
    style="max-width: 100px;">
```

**Comment by alvinkonda** [comment]
Does not happen often that the QTY field gets hidden, but anyway it seems your solution is fine, so I'm closing this.
