### ISSUE TITLE
Errors encountered

### ISSUE THREAD

**Issue by mrl22** [kondasoft/ks-bootshop#61]
Hello

Thank you for putting this theme together.

I have come to use it for the first time but on publishing I get the following error:

```
[development] Errors encountered: 
        [development] (templates/blog.json) Section type 'template-blog' does not refer to an existing section file
        [development] (templates/collection.json) Section type 'template-collection' does not refer to an existing section file
        [development] (templates/product.json) Filename product already exists with liquid extension, Section type 'template-product' does not refer to an existing section file, and Section type 'featured-products' does not refer to an existing section file
        [development] (templates/article.json) Filename article already exists with liquid extension and Section type 'template-article' does not refer to an existing section file
        [development] (templates/page.contact.json) Filename page.contact already exists with liquid extension and Section type 'contact-form' does not refer to an existing section file
        [development] (templates/index.json) Filename index already exists with liquid extension
```

Are you able to offer some advice?

**Comment by mrl22** [comment]
It seems they are only warnings and the theme publishes fine.

**Comment by alvinkonda** [comment]
if you have used the command `theme deploy` it seems those errors show up, as the `templates` folder is uploaded before the `sections` one, and so the Shopify CLI "thinks" those sections are missing. All you have to do is run another time the same command and it should be fine.

**Comment by mrl22** [comment]
Thank you. I have been working on the theme the last two days and all seems to be working perfectly. It has been a few years since I developed a Shopify and we use to use shopify-ftp package.
