### ISSUE TITLE
social-icons (whatsapp and email dont work)

### ISSUE THREAD

**Issue by bodingbauerre** [kondasoft/ks-bootshop#78]
if i activate email and whatsapp in the code (social_accounts in soical-icons.liquid) they aren't displayed

**Comment by alvinkonda** [comment]
I suppose you haven't added the settings in the `config_schema.json` file. Anyway, here is the full fix in the 2 files

https://github.com/kondasoft/ks-bootshop/commit/a83c719dd5b05b08a8da083b0b431dfdf1f58a3f
