### ISSUE TITLE
Connect theme social links to Shopify admin settings for the "brand" section

### ISSUE THREAD

**Issue by bacounts** [kondasoft/ks-bootshop#79]
With social links now being fields in the brand settings section of the admin, we can remove the social link settings from themes.

When a merchant sets values on the social link fields in brand settings, those will then surface directly on the theme.

**Navigate to brand settings:** https://[yourshopname].myshopify.com/admin/settings/branding

**Comment by alvinkonda** [comment]
Interesting, I'm just noticing that. There might be issues if the users want to add other icons that are not on that list, but still, we have to go on with what Shopify recommends.
