### ISSUE TITLE
Allow pulling variant level dynamic sources on the product page

### ISSUE THREAD

**Issue by bacounts** [kondasoft/ks-bootshop#80]
Currently, we can't pull dynamic sources at the variant level (like SKU, or variant-level metafields) on the product page.

As a buyer, as a select different variants, I should be able to see variant specific information displayed on the product page.

This is important for the base theme for simple maximized conversions.

**Comment by alvinkonda** [comment]
I have developed many Shopify stores, and displaying SKU is a pretty rare request. The same for variant-based metafields. But still, I will keep an eye on this in future developments. Thank you for your feedback.
