### ISSUE TITLE
Add a "Read more" button option to long descriptions

### ISSUE THREAD

**Issue by bacounts** [kondasoft/ks-bootshop#81]
A "Read more" button should be an option for long descriptions throughout the theme (i.e., Collection description, product description, custom meta fields on certain pages).

Some use longer text as an SEO strategy — while this practice is not ideal for most, it is still a common practice and should be accounted for as a setting within the editor.

**Example using the PLP:**
<img width="1084" alt="Screen Shot 2022-08-24 at 2 45 25 AM" src="https://user-images.githubusercontent.com/6481954/186387239-9d73529b-1ab4-41c8-9f2b-5b40c1f1930f.png">

**Comment by alvinkonda** [comment]
Thank you for your suggestion but our goal is to keep this theme simple and basic, and the readmore functionality is not fundamental for Shopify.
