### ISSUE TITLE
Product page returning 404

### ISSUE THREAD

**Issue by ukkpower** [kondasoft/ks-bootshop#89]
I have a test product in the store and the product page returns a 404. When using other templates the product can be viewed as expected.

When I go into the customise template area and click product from the template dropdown I get "No templates found for products"

https://traderiq.myshopify.com/

**Comment by alvinkonda** [comment]
Make sure this template is in the templates folder, otherwise, you should upload/create the file below.

https://github.com/kondasoft/ks-bootshop/blob/v4.0.1/templates/product.json

**Comment by ukkpower** [comment]
thanks, that worked perfectly. Great support

**Comment by alvinkonda** [comment]
That's great to hear. If you are interested in a premium version you can find it through the link below. Have a good day.

https://www.ecomifytheme.com/
