### ISSUE TITLE
Product images not showing on Product Page

### ISSUE THREAD

**Issue by Navjeet** [kondasoft/ks-bootshop#91]
Hi,

The product images not showing untill we add the image to variants.

Thanks

**Comment by alvinkonda** [comment]
Hello Navjeet,

Without having a look into your store there is not much that I can do for you.

Let me know.

**Comment by alvinkonda** [comment]
Please follow this thread as we noticed the issue

https://github.com/kondasoft/ks-bootshop/issues/92#issuecomment-1443065987
