### ISSUE TITLE
Product images are not showing up

### ISSUE THREAD

**Issue by iusty64** [kondasoft/ks-bootshop#94]
Do you know why this may be an issue?

**Comment by alvinkonda** [comment]
Please share your store URL so that we can check the issue

**Comment by iusty64** [comment]
www.sneakersvault.ro

**Comment by iusty64** [comment]
any idea?

**Comment by alvinkonda** [comment]
Sorry for the late reply. Can you please check this issue and let me know?

https://github.com/kondasoft/ks-bootshop/issues/92

**Comment by iusty64** [comment]
Hey, do I just replace 'product-gallery.liquid' in my shopify store with this one?(because they're the same and the issue still persists)

**Comment by alvinkonda** [comment]
As i have said please replace the content of the file I mentioned.

**Comment by iusty64** [comment]
I did and it didn’t work

**Comment by alvinkonda** [comment]
I have requested theme access to your store so that I can check. Let me know once you approve the request.

**Comment by iusty64** [comment]
Approved.

**Comment by EcomGraduatesDev** [comment]
Sorry fixed!

**Comment by alvinkonda** [comment]
Sorry fixed!

**Comment by alvinkonda** [comment]
Solution open `snippets/product-gallery.liquid`

Find:
```
    if product.has_only_default_variant 
        assign active_media_position = 1
    else 
        assign active_media_position = current_variant.featured_media.position
    endif

```

Replace it with:
```
    if product.has_only_default_variant 
        assign active_media_position = 1
    else 
        assign active_media_position = current_variant.featured_media.position | default: 1
    endif

```

**Comment by iusty64** [comment]
Thank you very much for the solution and help provided. Appreciate it!
