### ISSUE TITLE
In theme customization

### ISSUE THREAD

**Issue by Navjeet** [kondasoft/ks-bootshop#95]
I love your work, The section you have added is so fantastic, only the problem is that the sections are not working untill hit the save button in customization we can say in design mode. also it is quite confusing which section need to use as the repo has two section of each example like marque, testimonial.

Thank you

**Comment by alvinkonda** [comment]
Thanks for your kind words. You should download the new sections from our website. They also have a small PDF guide also, that clarifies which section to use.
