### ISSUE TITLE
Carousel section - image adapt setting

### ISSUE THREAD

**Issue by coblehartman** [kondasoft/ks-bootshop#96]
I'm having difficulty figuring out how to create a dynamic image that adjusts with the page's dimensions. For example, I can't just replace the sample image in the carousel with a new image and change it with the window. I'm not sure if this is a Shopify problem or a theme problem, but I've tried to adjust the carousel.liquid file directly and have had no luck. Any help would be appreciated.

**Comment by alvinkonda** [comment]
I made some improvements in the carousel section. Please replace the section with this new one.

Let me know if that solves the issue

https://github.com/kondasoft/ks-bootshop/blob/master/sections/carousel.liquid

<img width="2240" alt="Screenshot 2024-02-17 at 9 38 04 AM" src="https://github.com/kondasoft/ks-bootshop/assets/273284/290b4e16-4358-44de-a41c-2220de37de2e">

**Comment by coblehartman** [comment]
That did it! Thanks for the solution and the quick reply.
