### ISSUE TITLE
templates/page.liquid file has a wrong closing HTML tag

### ISSUE THREAD

**Issue by dennispio** [kondasoft/ks-bootshop#99]
Hey,
first of all awesome template thank you very much. 
There is a wrong Html-Tag in page.liquid.  
`<section>...</section>` or `<article>...</article>`

https://github.com/kondasoft/ks-bootshop/blob/master/templates/page.liquid

**Comment by alvinkonda** [comment]
Thanks for your kind words.

I fixed the closing tag for future releases, but it is not sth to worry about.
